# Generated by Django 6.0.7 on 2026-08-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_resume_experience_education_resumeproject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeproject',
            name='github_url',
            field=models.URLField(blank=True),
        ),
    ]
