# Generated by Django 6.0.7 on 2026-08-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_resumeproject_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeproject',
            name='built_with_cursor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resumeproject',
            name='demo_url',
            field=models.URLField(blank=True),
        ),
    ]
