# Generated by Django 6.0.7 on 2026-08-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_resumeproject_built_with_cursor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeproject',
            name='access_note',
            field=models.CharField(blank=True, help_text='Optional note about demo access (shown with an asterisk on the resume).', max_length=300),
        ),
    ]
