# Generated by Django 6.0.7 on 2026-08-01 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_resumeproject_access_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('image', models.ImageField(blank=True, help_text='Upload for image items.', null=True, upload_to='projects/gallery/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, Loom, or a direct .mp4/.webm link for video items.')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_items', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'Gallery item',
                'verbose_name_plural': 'Gallery items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
